<a href="https://colab.research.google.com/github/poorna305/poorna305/blob/main/numpy%26array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
 # scaler array
 a = np.array(5)
 a

array(5)

In [3]:
# dimension method
np.ndim(a)

0

In [4]:
#one dimension
one = np.array([1,2,3,4,5])

In [5]:
one

array([1, 2, 3, 4, 5])

In [6]:
np.ndim(one)

1

In [7]:
# two demension
two = np.array([[1,2,3,4], [6,7,8,9]])
two

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [8]:
np.ndim(two)

2

In [9]:
# three demension
three = np.array([[[1,2,3], [4,5,6] ,[7,8,9]]])
three

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
np.ndim(three)

3

In [11]:
list = [1,4,0,'apple']
arr = np.array([1,2,3,4,5])

In [12]:
#type conversion.
# all elements are same in the array eg:this all are string
arr = np.array([1,2,3.9,'apple'])
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [13]:
 arr = np.array([1,2,3,4,5])
 arr.sum()

15

In [14]:
# 1D to 2D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# 1Dto 3D array
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
# accessing array
arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [17]:
# addition of 2 elements
print(arr[1] + arr[3])

6


In [18]:
#accessing 2d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1]) #1st row and 2nd element
print(arr[1,2]) #2nd row and 3rd element

2
8


In [20]:
# accessing 3d array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])      #0th matrix, 2nd row , 3rd column
print(arr[1,0,1])      #1st matrix, 1st row, 2nd column

6
8


In [21]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

*slicing*

In [22]:
#slicing 1D array
a1 = np.array([1,2,3,4,5,6,7])
a1[1:5]

array([2, 3, 4, 5])

In [23]:
a1[4:]

array([5, 6, 7])

In [24]:
a1[:4]

array([1, 2, 3, 4])

In [25]:
#2D array
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2[1,1:4]

array([6, 7, 8])

In [26]:
a2[0:2,2]

array([3, 7])

In [27]:
a2[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
# 3D array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
a3[:2,1:,1:]

array([[[ 5,  6]],

       [[11, 12]]])

In [32]:
arr = np.array([1,2,3,4,5,6])
copy = arr.copy()
copy[0] = 42
print(arr)
print(copy)

[1 2 3 4 5 6]
[42  2  3  4  5  6]


In [33]:
view = arr.view()
view[0] = 42
print(arr)
print(view)

[42  2  3  4  5  6]
[42  2  3  4  5  6]


In [35]:
# append method
a = np.array([[1,2,3,],
             [4,5,6]])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.append(a,[[7,8,9]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.append(a,[[5],[7]],axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 7]])

In [39]:
# insert method
a = np.array([[1,2],
              [3,4],
              [5,6]])
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [40]:
np.insert(a,1,[11],axis = 0)

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [41]:
np.insert(a,1,11,axis = 1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [42]:
# delete method
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
np.delete(a,1,0)

array([[1, 2, 3],
       [7, 8, 9]])

In [43]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [44]:
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [45]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

In [46]:
result = np.hstack((a,b))
result

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [47]:
result = np.vstack((a,b))
result

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [49]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.array([[3],[4]])
arr4 = np.array([[5],[6]])

In [50]:
new = np.concatenate((arr1,arr2),axis = 1)
new

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
new = np.concatenate((arr1,arr2),axis = 0)
new

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])